/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const Millis = t.name('number')

export const EventType = t.union(t.lit('image'), t.lit('audio'))

export const EventBase = t.iface([], {
  id: 'string',
  name: 'string',
  timestamp: 'Millis',
  type: 'EventType',
})

export const ImageEvent = t.iface(['EventBase'], {
  type: t.lit('image'),
  payload: t.iface([], {
    url: 'string',
  }),
})

export const AudioEvent = t.iface(['EventBase'], {
  type: t.lit('audio'),
  payload: t.iface([], {
    url: 'string',
  }),
})

export const Event = t.union('ImageEvent', 'AudioEvent')

export const Events = t.array('Event')

const exportedTypeSuite: t.ITypeSuite = {
  Millis,
  EventType,
  EventBase,
  ImageEvent,
  AudioEvent,
  Event,
  Events,
}
export default exportedTypeSuite
